
packaging_format = 2

name = "Trivabble"
id = "trivabble"

description.en = "a network Scrabble® game free play not enforcing rules"
description.fr = "un jeu de Scrabble® en jeu libre, à l'utilisateur d'appliquer les règles."

version = "2021.08.05~ynh10"
license = "AGPL-3.0-or-later"

[upstream]
url = "https://trivabble.org/"
license = "AGPL-3.0-or-later"

[maintainer]
name = "Philippe Lhardy"
email = "pl@artisanlogiciel.net"
url = "https://www.artisanlogiciel.net"

[integration]
architectures = "all"
yunohost = ">= 12.0.0"
helpers_version = "2.1"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/trivabble"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.apt]
    packages = ["rsync"]

    [resources.system_user]

    [resources.sources.main]
    url = "https://git.jakse.fr/trivabble/trivabble/archive/prod-v20210805.tar.gz"
    sha256 = "47869c5c9c8c625e36bfde5ff51ab0c470f6354fe2472ebf9181a2c9d385405c"

    [resources.nodejs]
    version = "22"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
