#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

final_path=$(ynh_app_setting_get --app=$app --key=final_path)
domain=$(ynh_app_setting_get --app=$app --key=domain)
db_name=$(ynh_app_setting_get --app=$app --key=db_name)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping a systemd service..." --time --weight=1

ynh_systemctl --service=$app --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_script_progression "Backing up the main app configuration " --time --weight=1

# if we want to save only config...
# ynh_backup "$final_path/server/games.backup.json"
# ynh_backup "$final_path/public/config.js"

# full app with code... seems to be default way...
ynh_backup "$final_path"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Backing up nginx web server configuration..." --time --weight=1

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP THE MYSQL DATABASE
#=================================================
# no SQL like database, embeded data file
#ynh_script_progression "Backing up the MySQL database..." --time --weight=1

#ynh_mysql_dump_db --database="$db_name" > db.sql

#=================================================
# BACKUP FAIL2BAN CONFIGURATION
#=================================================

# no fail2ban
#ynh_script_progression "Backing up fail2ban configuration..." --time --weight=1

#ynh_backup "/etc/fail2ban/jail.d/$app.conf"
#ynh_backup "/etc/fail2ban/filter.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP LOGROTATE
#=================================================
ynh_script_progression "Backing up logrotate configuration..." --time --weight=1

ynh_backup "/etc/logrotate.d/$app"

#=================================================
# BACKUP SYSTEMD
#=================================================
ynh_script_progression "Backing up systemd configuration..." --time --weight=1

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# BACKUP A CRON FILE
#=================================================

# no cron related action ( yet ?)
# ynh_backup "/etc/cron.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting a systemd service..." --time --weight=1

ynh_systemctl --service=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)." --time --last
