#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

username=${username:-$app}
groupname=${groupname:-$app}

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# no custom settings yet

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

source unpackinstall

# Set right permissions for curl install
chown -R $username $install_dir

# TWEAK trivabble client configuration

ynh_script_progression "Create client configuration for this app path $path_url" --time --weight=1

cat <<EOF >$install_dir/public/config.js
window.TrivabbleConf = {
    APP_PATH: "$path_url"
}
EOF

chown -R root $install_dir

# Set permissions to app files
chown -R www-data:www-data $install_dir
chown -R $username:$groupname $install_dir/server

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Trivabble game web server service" --log="/var/log/$app/$app.log"

mkdir -p "/var/log/$app"
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
