#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

### If the app uses nginx as web server (written in HTML/PHP in most cases), the final path should be "/var/www/$app".
### If the app provides an internal web server (or uses another application server such as uwsgi), the final path should be "/opt/yunohost/$app"
final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

install_dir=${final_path}
# assuming $install_dir == $finalpath in systemd.service
username=${username:-$app}
groupname=${groupname:-$app}

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# no custom settings yet

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

source unpackinstall

# Set right permissions for curl install
chown -R $username $final_path

# TWEAK trivabble client configuration

ynh_script_progression "Create client configuration for this app path $path_url" --time --weight=1

cat <<EOF >$final_path/public/config.js
window.TrivabbleConf = {
    APP_PATH: "$path_url"
}
EOF

chown -R root $final_path

# Set permissions to app files
chown -R www-data:www-data $final_path
chown -R $username:$groupname $final_path/server

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Trivabble game web server service" --log="/var/log/$app/$app.log"

mkdir -p "/var/log/$app"
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
