#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

### If the app uses nginx as web server (written in HTML/PHP in most cases), the final path should be "/var/www/$app".
### If the app provides an internal web server (or uses another application server such as uwsgi), the final path should be "/opt/yunohost/$app"
final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

# because __FINALPATH__ in nginx.conf
finalpath=${final_path}
install_dir=${final_path}
# assuming $install_dir == $finalpath in systemd.service ?
echo "$finalpath == $install_dir ?"
username=${username:-$app}
groupname=${groupname:-$app}

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

source unpackinstall

# Set right permissions for curl install
chown -R $username $final_path

# TWEAK trivabble client configuration

ynh_script_progression "Create client configuration for this app path $path_url" --time --weight=1

cat <<EOF >$final_path/public/config.js
window.TrivabbleConf = {
    APP_PATH: "$path_url"
}
EOF

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring nginx web server..." --time --weight=1

# Create a dedicated nginx config conf/nginx.conf
ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Trivabble game web server service" --log="/var/log/$app/$app.log"

mkdir -p "/var/log/$app"
ynh_config_add_logrotate

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

### For security reason, any app should set the permissions to root: before anything else.
### Then, if write authorization is needed, any access should be given only to directories
### that really need such authorization.
chown -R root $final_path

# Set permissions to app files
chown -R www-data:www-data $final_path
chown -R $username:$groupname $final_path/server

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting a systemd service..." --time --weight=1

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed" --time --last
