#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression "Loading installation settings..." --time --weight=1

domain=$(ynh_app_setting_get --app=$app --key=domain)
port=$(ynh_app_setting_get --app=$app --key=port)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by Yunohost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app
then
	ynh_script_progression "Removing $app service..." --time --weight=1
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..." --time --weight=1

# Remove the dedicated systemd config
ynh_config_remove_systemd

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression "Removing app main directory..." --time --weight=1

ynh_safe_rm "$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx web server configuration..." --time --weight=1

# Remove the dedicated nginx config
ynh_config_remove_nginx

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..." --time --weight=1

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_script_progression "Closing port $port..."
	ynh_hide_warnings yunohost firewall disallow TCP $port
fi

#=================================================
# REMOVE FAIL2BAN CONFIGURATION
#=================================================
ynh_script_progression "Removing fail2ban configuration..." --time --weight=1

# Remove the dedicated fail2ban config
ynh_config_remove_fail2ban

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE THE CRON FILE
#=================================================

# Remove a cron file
ynh_safe_rm "/etc/cron.d/$app"

# Remove a directory securely
ynh_safe_rm "/etc/$app/"

# Remove the log files
ynh_safe_rm "/var/log/$app/"

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression "Removing the dedicated system user..." --time --weight=1

# Delete a system user
ynh_system_user_delete --username=$app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed" --time --last
