#!/bin/bash

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --time --weight=1

### `ynh_setup_source` is used to install an app from a zip or tar.gz file,
### downloaded from an upstream source, like a git repository.
### `ynh_setup_source` use the file conf/app.src

ynh_app_setting_set --app=$app --key=final_path --value=$final_path

# temporary intermediate directory since it contains more files than needed
src_filename=$trivabble_git_tag.tmp_src

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$src_filename"

# required to build i10n client support 
pushd "$src_filename"
make
popd

# check that l10n build succeeded
if [[ ! -d $src_filename/public/l10n/js ]] ; then
    echo "list content of  $src_filename for forensics" >&2
    # to have some trace  of what did fail
    find  $src_filename/
    ynh_die "expected public js directory for i10n not found in $(pwd)/$src_filename"
fi

# deliver it to $final_path ( hack copy subpart of bin/upgrade-prod.sh )

echo "Sending to production..."

WORKING_DIRECTORY=$src_filename
PROD_PUBLIC_DIR=$final_path/public
PROD_SERVER_DIR=$final_path/server

mkdir -p $PROD_PUBLIC_DIR
mkdir -p $PROD_SERVER_DIR

rsync -avp --delete --exclude 'config.js' "$WORKING_DIRECTORY/public/" "$PROD_PUBLIC_DIR/"
rsync -avp --delete --exclude 'config.js' "$WORKING_DIRECTORY/server/" "$PROD_SERVER_DIR/"

rm -rf $src_filename

# Download, check integrity, uncompress and patch the source from app.src
# ynh_setup_source --dest_dir="$final_path"
